# de quanto em quanto tempo o promewtheus busca as metricas

scrape_configs:
  - job_name: 'banking-service-app'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']